### Numpy Mastery Assignment
- Answer all questions

In [1]:
import numpy as np

1. Create a 1D array of numbers from 0 to 9

In [4]:
my_array1 = np.arange(0,10)
my_array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3x3 numpy of all True 

In [7]:
my_array2 = np.ones((3,3), dtype = bool)
my_array2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [9]:
my_array3 = np.arange(20, 40)
my_array3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [12]:
my_array3 [my_array3 % 2 != 0] = -1
my_array3

array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

5. Create two arrays of length 10 and print out  common items in both arrays

In [21]:
my_array4 = np.arange(45,56)
my_array5 = np.arange(49,60)
common_numbers = np.intersect1d(my_array4, my_array5)
common_numbers

array([49, 50, 51, 52, 53, 54, 55])

6.  Create a 5x5 identity matrix

In [22]:
mat_5x5 = np.matrix(np.arange(1,26))
mat_5x5.reshape (5,5)

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [35]:
x = np.array ([10, 12, 9, 2, 19])
y = np.linspace (10, 20, 101)
z = np.ones ((2,3), dtype = int)

print(f"x = {x}")
print(f"y = {y}")
print(f"z = {z}")

x = [10 12  9  2 19]
y = [10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9 20. ]
z = [[1 1 1]
 [1 1 1]]


8. Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [38]:
mean_x = np.mean(x)
std_x = np.std(x)
print(f"mean of x = {mean_x}")
print(f"standard deviation of x = {round(std_x, 3)}")

mean of x = 10.4
standard deviation of x = 5.463


9. Create a 10x10 array with random values and find the minimum and maximum values

In [55]:
ten_by_ten = np.random.randint(4,350,size = 100)
ten_by_ten.reshape(10,10)

array([[160, 304, 330, 122, 271,  89, 218, 328, 142, 154],
       [265, 326,  34,  60, 195, 167, 327, 244,  37, 336],
       [201, 326, 126,  75,  90, 121,  57,  35, 265, 339],
       [264,  39,  80,  50, 214, 185,  32, 310, 225,  67],
       [315, 311, 239,  56, 189, 222, 161, 316, 272, 310],
       [326, 140, 181, 103, 148, 117, 199,  66, 140, 210],
       [247,  44,  95, 103, 266, 100,  13, 217, 332, 140],
       [181,  35, 243, 336, 137, 166, 118,  80, 346, 205],
       [120, 252,  94,  39, 189, 310, 267,  76, 277, 257],
       [282,   4, 339,  70,  17, 321,   8,  98, 334, 115]])

In [56]:
# maximum value of the random integers
np.max(ten_by_ten)

346

In [57]:
# minimum value of the random integers
np.min(ten_by_ten)

4

10. Create a 3x3 matrix with values ranging from 0 to 8

In [66]:
three_by_three_matrix = np.matrix(np.arange(0,9)).reshape((3,3))
three_by_three_matrix

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

11.  Generates an array [[1 2 3] [4 5 6]]

In [72]:
my_array_8 = np.array(np.arange(1,7)).reshape(2,3)
my_array_8

array([[1, 2, 3],
       [4, 5, 6]])

12. Generates an array [0 2.5 5 7.5 10]

In [100]:
my_array_9 = np.array(np.arange(0,11,2.5))
my_array_9

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

13. Generates an 3x3 array of zeros

In [85]:
my_array_10 = np.array(np.zeros((3,3)))
my_array_10

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. Create array from 0.1 to 10 with 12 elements, inclusively

In [105]:
my_array_11 = np.linspace(0.1,10,12)
my_array_11

array([ 0.1,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. ])

15. Create a matrix with seven columns and five rows of ten(10).

In [136]:
my_array_12 = np.full((5,7),10)
my_array_12

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

16. What is the difference between numpy and list?

In [137]:
# Numpy is more memory efficient than a list, and it can also run codes faster.

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [138]:
my_array_13 = np.ones(50)
my_array_13[1::2] = 0
my_array_13

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [139]:
my_array_14 = np.eye(10)
my_array_14

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [140]:
my_array_111 = np.eye(10)
my_array_111

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [141]:
mat_1 = [[1,2],[3,4]]
mat_2 = [[5,6],[7,8]]
np.dot (mat_1, mat_2)

array([[19, 22],
       [43, 50]])

21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [142]:
one = np.matrix([[1,2],[3,4]])
two = np.matrix([[5,6],[7,8]])
one * two

matrix([[19, 22],
        [43, 50]])

22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [143]:
this_matrix = np.matrix([[1,2],[3,4]])
5 * this_matrix

matrix([[ 5, 10],
        [15, 20]])

23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

In [144]:
A = np.matrix([[1,2],[3,4]])
B = A.transpose()
B

matrix([[1, 3],
        [2, 4]])

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [145]:
A = np.array ([[1,2],[3,4]])
B = np.array ([[5,6],[7,8]])
A * B

array([[ 5, 12],
       [21, 32]])

In [146]:
B * A

array([[ 5, 12],
       [21, 32]])

In [147]:
# they are the same

25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [148]:
F = np.array([[0, 1, 2], [3, 4, 5]])
F

array([[0, 1, 2],
       [3, 4, 5]])

In [159]:
A = F[0,:]
B = F[1,:]
C = F[:,1]
D = F[0,2]

In [160]:
A

array([0, 1, 2])

In [161]:
B

array([3, 4, 5])

In [162]:
C

array([1, 4])

In [154]:
D

2